### ISSUE TITLE
IndentationError: unexpected indent

### ISSUE THREAD

**Issue by VChristlein** [huggingface/competitions#23]
I'll give it one more try as it seems the support is very fast - thank you for this! 

After hitting `Factory rebuild`, I get the following error:

```
===== Application Startup at 2024-02-26 12:12:27 =====


==========
== CUDA ==
==========

CUDA Version 12.1.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

Traceback (most recent call last):
  File "/app/env/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/app/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/app/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/app/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/app/env/lib/python3.10/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/app/env/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/app/env/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/app/env/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/app/env/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/env/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/app/env/lib/python3.10/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/app/env/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/app/env/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/competitions/app.py", line 100
    return RedirectResponse("/login/huggingface")
IndentationError: unexpected indent
ERROR conda.cli.main_run:execute(124): `conda run /bin/bash -c uvicorn competitions.app:app --host 0.0.0.0 --port 7860 --workers 1` failed. (See above for error)

```

**Comment by abhishekkrthakur** [comment]
i apologize for the issue. code made it to production accidently. issue has been resolved now and image is being deployed. it takes ~10mins to push new image. factory rebuild after that will fix the problem.

**Comment by abhishekkrthakur** [comment]
fix has been deployed. please factory rebuild the competition space or create a new one.
