### ISSUE TITLE
[URGENT] uvicorn error

### ISSUE THREAD

**Issue by qiyan98** [huggingface/competitions#25]
Hi there,

We continue to encounter this error (see below) despite numerous attempts to reboot or rebuild our HuggingFace competition space. Users are currently unable to use their tokens to submit results, although the other parts of the website appear to be functioning correctly.

Our space is located at https://huggingface.co/spaces/CPEN455-23W2/CPEN45523W2CourseProject. We urgently need to resolve this issue so that students can use it to upload their project results. Any assistance would be greatly appreciated!

Thanks,
Alex

```
===== Application Startup at 2024-04-10 01:08:01 =====


==========
== CUDA ==
==========

CUDA Version 12.1.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

INFO:     Started server process [35]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7860 (Press CTRL+C to quit)
INFO:     10.16.25.191:42901 - "GET / HTTP/1.1" 200 OK
INFO:     10.16.25.191:42901 - "GET / HTTP/1.1" 200 OK
INFO:     10.16.25.191:42901 - "GET /competition_info HTTP/1.1" 200 OK
INFO:     10.16.25.191:42901 - "GET /use_oauth HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/env/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/app/env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/app/env/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/app/env/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 70, in app
    response = await func(request)
  File "/app/env/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/app/env/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/app/env/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/competitions/app.py", line 129, in use_oauth
    if request.session.get("oauth_info") is not None:
  File "/app/env/lib/python3.10/site-packages/starlette/requests.py", line 148, in session
    "session" in self.scope
AssertionError: SessionMiddleware must be installed to access request.session
```

**Comment by qiyan98** [comment]
Hi @abhishekkrthakur @glegendre01 @mishig25 , could you please take a look at this issue? Thanks!

**Comment by abhishekkrthakur** [comment]
Can you add a variable USE_OAUTH with value 1 and rebuild the space?

tiny keyboard, tiny message

**Comment by abhishekkrthakur** [comment]
Can you add a variable USE_OAUTH with value 1 and rebuild the space?

**Comment by qiyan98** [comment]
Thanks for your suggestions!
I actually need to set `USE_OAUTH` to 0 to make it work.

```
ENV USE_OAUTH=0
```

I had this line inf the `Dockerfile` and the bug is gone.

**Comment by abhishekkrthakur** [comment]
you should set it in the settings page of competition space. it seems like the competiton was created a while ago and this value was missing. ill take a look why. New competitions dont have this issue. Glad its fixed now :)

**Comment by qiyan98** [comment]
Anyway, setting `USE_OAUTH=1` in settings env doesn't seem to work in our case. I will stick to my own hack to make it work for now...

**Comment by abhishekkrthakur** [comment]
@qiyan98 could you add me to the organization organizing the competition so i can debug whats wrong with oauth and push some changes? my huggingface username is `abhishek`

**Comment by abhishekkrthakur** [comment]
okay, i got it.
please add the following to your README for competition space:

```
hf_oauth: true
hf_oauth_scopes:
  - read-repos
```

then remove your changes to dockerfile and do a factory rebuild, please. using oauth is preferred over token. :)

**Comment by qiyan98** [comment]
Thanks! This works perfectly. @abhishekkrthakur
