### ISSUE TITLE
Submission Error

### ISSUE THREAD

**Issue by HuangZhen02** [huggingface/competitions#31]
I create a generic competition and try to submit a json file for testing. 

I manually delete the submissions and submission_info folders after one successful submission (as I find something error in my evaluation metric script). Then, I do **Factory rebuild** after fixing my metric script.

However, some errors occurred when I do additional submissions:

```
SyntaxError: Unexpected token 'I', "Internal S"... is not valid JSON
```
```
INFO:     10.16.14.230:12616 - "POST /new_submission HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/env/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 286, in hf_raise_for_status
    response.raise_for_status()
  File "/app/env/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/datasets/XXX/XXXXXXX/resolve/main/submission_info/189c34e8-4453-457a-8dab-b7f808e6ad98.json

Entry Not Found for url: https://huggingface.co/datasets/XXX/XXXXXXX/resolve/main/submission_info/189c34e8-4453-457a-8dab-b7f808e6ad98.json.
```

**Comment by lennart-maack** [comment]
How did you fix that error?
