### ISSUE TITLE
Error in fetch_leaderboard

### ISSUE THREAD

**Issue by lennart-maack** [huggingface/competitions#49]
Hi,

I am currently running a competition for a university project ([https://huggingface.co/spaces/Mtec-Tuhh/ISMChallengePhase1a](https://huggingface.co/spaces/Mtec-Tuhh/ISMChallengePhase1a)) and have done a factory rebuild to reinstall some required libraries. Previously the public leaderboard was displaying correctly. Unfortunately, after reinstalling the factory, I get the following error when I try to access the public leaderboard:

2024-12-02 13:55:40.787 | INFO     | competitions.leaderboard:_process_public_lb:35 - Downloaded submissions in 0.029535531997680664 seconds
INFO:     10.20.38.195:50576 - "POST /leaderboard HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/env/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/app/env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 85, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/app/env/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/app/env/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/app/env/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/app/env/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/competitions/app.py", line 209, in fetch_leaderboard
    df = leaderboard.fetch(private=lb == "private")
  File "/app/competitions/leaderboard.py", line 156, in fetch
    submissions = self._process_public_lb()
  File "/app/competitions/leaderboard.py", line 68, in _process_public_lb
    user_submissions.sort(key=lambda x: x[self.scoring_metric], reverse=self.eval_higher_is_better)
  File "/app/competitions/leaderboard.py", line 68, in <lambda>
    user_submissions.sort(key=lambda x: x[self.scoring_metric], reverse=self.eval_higher_is_better)
KeyError: 'f1_score'

Do you need more information?

Thank you in advance
Lennart

**Comment by abhishekkrthakur** [comment]
It seems like one of the submissions doesn't have the `f1_score` field?

**Comment by abhishekkrthakur** [comment]
please check the `submission_info` folder in competition config repo. there, there is probably an invalid submission without f1_score field. deleting that will fix the issue. please let me know if you need further assistance.

**Comment by lennart-maack** [comment]
Thank you for your quick reply. I will check asap.
Does this apply to '"selected": true' only? Or should I also check '"selected": false' as well?

**Comment by abhishekkrthakur** [comment]
it should apply to all submissions with a success flag. so probably, the metrics were botched, but submission was marked as success. are you using custom metrics?

**Comment by lennart-maack** [comment]
Yes, I do use custom metrics.
There are over >100 submission, so I will take a while until I checked and cleaned everything. Will let you know asap

**Comment by abhishekkrthakur** [comment]
then probably a submission was marked as success but the metrics were not returned. please make sure your custom metrics throw an error instead of passing when metrics are not returned and mark submsission as failed.

to make it easy to find, you could look at latest commits. that will be easier if you have many submissions. :) 

please let me know if i can be of any help :)

**Comment by lennart-maack** [comment]
I cleaned all invalid submission (submissions without a f1_score key) and the leaderboard is working again. 
Thank you!
