### ISSUE TITLE
support for custom metrics

### ISSUE THREAD

**Issue by Josephrp** [huggingface/competitions#9]
would be great to have the right metrics and outcomes for the image gen community :-)

**Comment by abhishekkrthakur** [comment]
in next release, you should be able to define your own metric (next week). ill keep this issue open till then

**Comment by abhishekkrthakur** [comment]
https://huggingface.co/docs/competitions/custom_metric
select metric: custom from the dropdown in creator space.

**Comment by Josephrp** [comment]
well, she's a beauty ! i've been testing and enjoying all the new features and the competition creators, they are great.

![image](https://github.com/huggingface/competitions/assets/18212928/65a77b99-641d-4b50-9578-f8481401af76)

so here it's a script competition with custom metrics, and i did add a solution.csv with correct headers, but the submission input accepts only two fields so there's a mismatch i think (my own hypothesis :-) ) 

one suggestion is to also autogenerate the solution.csv based on the creator inputs , and then generate the solution input fields i guess plain text for inputs , but i'm not sure and perhaps it's more clear simply to create the solution.csv directly based on the two current fields of the custom metric's solution submission.

the second one works for me fine, i'll try to modify the csv accordingly now and see.

**Comment by Josephrp** [comment]
```bash
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/env/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/app/env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/app/env/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/app/env/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 70, in app
    response = await func(request)
  File "/app/env/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/app/env/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/app/env/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/competitions/app.py", line 156, in new_submission
    end_date=COMP_INFO.end_date,
  File "/app/competitions/info.py", line 76, in end_date
    return datetime.strptime(e_d, "%Y-%m-%d")
  File "/app/env/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/app/env/lib/python3.10/_strptime.py", line 534, in _strptime
    julian = datetime_date(year, month, day).toordinal() - \
ValueError: day is out of range for month
```

something

**Comment by abhishekkrthakur** [comment]
please check your conf.json in private repo and make sure date format is YYYY-MM-DD. once you fix it, factory rebuild the competition space :)
